version: '3.7'

services:
  app:
    image: inventory-app:local
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.dev
    environment:
      OPCACHE_VALIDATE_TIMESTAMPS: 1
      ENV: dev
    volumes:
      - ./app:/var/www/html:rw,cached
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./app/public:/var/www/html/public
      - ./docker/nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  database:
      image: mysql:latest
      environment:
        MYSQL_DATABASE: mysqldb
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpassword
      volumes:
        - db_data:/var/lib/mysql:rw
volumes:
  db_data: {}
